# Generated by Django 3.2.6 on 2021-08-31 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flr', '0002_auto_20210823_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_lists',
            name='Email',
            field=models.EmailField(max_length=254, verbose_name=django.core.validators.EmailValidator),
        ),
        migrations.AlterField(
            model_name='user_lists',
            name='Username',
            field=models.CharField(max_length=20),
        ),
    ]
