# Generated by Django 3.2.6 on 2021-08-23 10:04

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('flr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user_lists',
            managers=[
                ('person', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='user_lists',
            name='Mobile_No',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
